name: analog_clock
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  flutter_svg: ^0.18.0
  provider: ^4.3.2+1
  splashscreen:
  intl: ^0.16.1
  flutter_local_notifications: ^1.4.4+2
  sqflite: ^1.3.1+1
  dotted_border: ^1.0.6
  firebase_messaging: ^7.0.3
  android_alarm_manager: ^0.4.5+15
  audioplayers: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/other/
    - assets/
  fonts:
    - family: avenir
      fonts:
        - asset: assets/other/fonts/Avenir-Book.ttf
        - asset: assets/other/fonts/Avenir-Heavy.ttf
          weight: 700
        - asset: assets/other/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/other/fonts/Avenir-Light.ttf
          weight: 300
